version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo current working dir
      - pwd
      - echo current files list
      - ls -la
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t prd_lsb_ecs_service:$IMAGE_TAG .
      - docker tag prd_lsb_ecs_service:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo current working dir
      - pwd
      - echo current files list
      - ls -la
      - echo Writing image definitions file...
      - printf '[{"name":"prd_lsb_ecs_service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Creating AppSpec file...
      - cat appspec.yaml
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml