version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-1:992382638511:task-definition/dev_lsb_family"
        LoadBalancerInfo:
          ContainerName: "dev_lsb_container"
          ContainerPort: 8080